# Generated by Django 5.1.1 on 2024-10-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvel',
            name='Heroic_name',
        ),
        migrations.AddField(
            model_name='marvel',
            name='Email',
            field=models.EmailField(default='NA', max_length=50),
        ),
    ]
